#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PCAuditReader.Resource", IsApplication=true)]

namespace PCAuditReader
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::PCAuditReader.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::PCAuditReader.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::PCAuditReader.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconQR = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int layout_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int btnBack = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int btnNetwork = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int btnPeripherals = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnPrinters = 2131034124;
			
			// aapt resource value: 0x7f050033
			public const int btnScan = 2131034163;
			
			// aapt resource value: 0x7f050009
			public const int btnSoftware = 2131034121;
			
			// aapt resource value: 0x7f050034
			public const int btnUpdate = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int btnViewMore = 2131034162;
			
			// aapt resource value: 0x7f050036
			public const int contentFrame = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int imageView1 = 2131034165;
			
			// aapt resource value: 0x7f05000b
			public const int lbButtons = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int lbButtons2 = 2131034120;
			
			// aapt resource value: 0x7f050014
			public const int lblAuditDate = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int lblAuditor = 2131034134;
			
			// aapt resource value: 0x7f05002e
			public const int lblAvailSpace = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int lblComments = 2131034160;
			
			// aapt resource value: 0x7f05001c
			public const int lblComputerName = 2131034140;
			
			// aapt resource value: 0x7f05002c
			public const int lblHardDriveSize = 2131034156;
			
			// aapt resource value: 0x7f050018
			public const int lblManufacturer = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int lblModel = 2131034138;
			
			// aapt resource value: 0x7f050005
			public const int lblMulti = 2131034117;
			
			// aapt resource value: 0x7f05001e
			public const int lblOS = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int lblOSArch = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int lblProcessName = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int lblProcessorsNo = 2131034152;
			
			// aapt resource value: 0x7f05002a
			public const int lblRam = 2131034154;
			
			// aapt resource value: 0x7f050024
			public const int lblSerialNo = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int lblServicePack = 2131034146;
			
			// aapt resource value: 0x7f050004
			public const int lblSingle = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int lblSoftwareName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int lblSoftwareVendor = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int lblSoftwareVersion = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int lnBackground = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int lnFields = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int lnScroll = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int lnTextfields = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int lstItems = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int scrollView1 = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int sqlite_id = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int txtAuditDate = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int txtAuditor = 2131034135;
			
			// aapt resource value: 0x7f05002f
			public const int txtAvailSpace = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int txtComments = 2131034161;
			
			// aapt resource value: 0x7f05001d
			public const int txtCompName = 2131034141;
			
			// aapt resource value: 0x7f05002d
			public const int txtHardDriveSize = 2131034157;
			
			// aapt resource value: 0x7f050019
			public const int txtManu = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int txtModel = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int txtOS = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int txtOSArch = 2131034145;
			
			// aapt resource value: 0x7f050027
			public const int txtProcessName = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int txtProcessorsNo = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public const int txtRam = 2131034155;
			
			// aapt resource value: 0x7f050025
			public const int txtSerialNo = 2131034149;
			
			// aapt resource value: 0x7f050023
			public const int txtServicePack = 2131034147;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomRowSmall = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListInfo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SplashScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscanneractivitylayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscannerfragmentlayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
